#!/usr/bin/env node
// GENERATE public/palettes.css FROM docs/palettes.json (3.4.0, ADR-0110).
//
// PALETTES.md §6 says this in as many words, and it is the reason this file
// exists rather than five more blocks hand-written into app.css:
//
//   "Before adding families, consolidate. If a palette is currently declared in
//    N places, adding F families makes it N x F x 2 blocks that must never
//    drift — and this family has already been bitten repeatedly by
//    must-change-together token definitions."
//
// Quietkeep declared its colours in four places before this: `:root`, a
// `--dark-*` mirror, and two mapping blocks. Five families would have been
// twenty blocks nobody could hold in their head.
//
// So the JSON is the ONE source and this writes the CSS, the same arrangement
// CHANGELOG.md already has with `src/ui/changelog.ts`. `--check` fails on drift
// and is what CI runs; nothing regenerates in CI, because regenerating the
// artefact a gate checks repairs the drift instead of reporting it.

import { readFileSync, writeFileSync } from 'node:fs';

const SRC = 'docs/palettes.json';
const OUT = 'public/palettes.css';
const CHECK = process.argv.includes('--check');

const set = JSON.parse(readFileSync(SRC, 'utf8'));
const families = Object.entries(set.families ?? {});
const def = set.default;
if (!families.length) { console.error(`${SRC} defines no families.`); process.exit(1); }
if (!set.families[def]) { console.error(`${SRC}: default "${def}" is not a family.`); process.exit(1); }

const block = (sel, roles, indent = '') => `${indent}${sel} {\n`
  + Object.entries(roles).map(([r, v]) => `${indent}  --${r}: ${v};`).join('\n')
  + `\n${indent}}\n`;

/* THE DEFAULT IS DECLARED WITHOUT AN ATTRIBUTE, and that is not a style choice.
 *
 * This app cannot know the reader's palette before first paint: `localStorage`
 * is banned outright, the choice lives in IndexedDB which is async, and the CSP
 * forbids the inline one-liner PALETTES.md assumes. So SOMETHING has to be on
 * screen before the answer arrives, and it has to be the default.
 *
 * What that costs is one beat of the default palette on a cold start for a
 * reader who chose another — in the RIGHT MODE, because `prefers-color-scheme`
 * is answerable before paint even when the palette is not. A hue changing is a
 * far smaller thing to see than light turning into dark. */
let css = `/* GENERATED by \`npm run palettes\` from ${SRC}. DO NOT EDIT.
 *
 * Palette and mode are independent axes (hub PALETTES.md §6):
 *   <html data-palette="paper" data-theme="dark">
 *
 * Value blocks only — no new token names, so a reskin stays a drop-in swap and
 * every rule in app.css goes on reading the same seven roles. */

/* The default family, unattributed: it is what paints before the reader's own
   choice can be read out of IndexedDB. */
${block(':root', set.families[def].light)}
@media (prefers-color-scheme: dark) {
${block(':root:not([data-theme="light"])', set.families[def].dark, '  ')}}
${block(':root[data-theme="dark"]', set.families[def].dark)}${block(':root[data-theme="light"]', set.families[def].light)}`;

for (const [key, f] of families) {
  css += `\n/* ${f.name} — ${f.why ?? ''} */\n`;
  css += block(`:root[data-palette="${key}"]`, f.light);
  css += `@media (prefers-color-scheme: dark) {\n`
    + block(`:root[data-palette="${key}"]:not([data-theme="light"])`, f.dark, '  ') + `}\n`;
  css += block(`:root[data-palette="${key}"][data-theme="dark"]`, f.dark);
  css += block(`:root[data-palette="${key}"][data-theme="light"]`, f.light);
}

if (CHECK) {
  let have = '';
  try { have = readFileSync(OUT, 'utf8'); } catch { /* missing is drift */ }
  if (have === css) {
    console.log(`\n  ok    ${OUT} is what ${SRC} says it should be`);
    console.log(`        ${families.length} families, ${families.length * 2} palettes\n`);
    process.exit(0);
  }
  console.error(`\n  FAIL  ${OUT} has drifted from ${SRC}.`);
  console.error('        The JSON is the source. Run:  npm run palettes\n');
  process.exit(1);
}
writeFileSync(OUT, css);
console.log(`wrote ${OUT} — ${families.length} families, ${families.length * 2} palettes`);
